name = "kesim"
workers_dev = false
account_id = "f6eb193c5ada002251ec96253583e74d"
routes = [
  "kes.im/*",
  "api.kes.im/*"
]
main = "workers-site/index.js"
compatibility_date = "2023-03-12"

[[kv_namespaces]]
binding = "kesim_data"
id = "767fc2258dd94aa09ddcacdac19b1e23"

[site]
bucket = "./public"

[vars]
CF_TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"
